export const ActionTypes={
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS:"REMOVE_SELECTED_PRODUCTS",
    INCREASE_COUNT:"INCREASE_COUNT",
    CHANGE_IMAGE_AND_COUNT:"CHANGE_IMAGE_AND_COUNT",
    SET_INITIAL_PRODUCT:"SET_INITIAL_PRODUCT",
    
}